# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default

objects:
 -
   model: rbares_cart
   default_link: link_0
 -
   model: rbares_cart_0
   default_link: link_0
 -
   model: rbares_cart_1
   default_link: link_0

robots:
- 
   model: rbares_a
   default_link: rbares_a_base_footprint
- 
   model: rbares_b
   default_link: rbares_b_base_footprint
- 
   model: rbares_c
   default_link: rbares_c_base_footprint

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
